### ISSUE TITLE
 Activity: declare and name variables problem in quiz

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#276]
@remisharrock @petraBT can you look at that and confirm that this is OK. I will clear students attempts. 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551

**Comment by petraBT** [comment]
Thanks, Ella! I fixed that quiz earlier, so yes, please do clear the students' attempts so that they can go again.

**Comment by remisharrock** [comment]
thanks. and also inform them on the forum that they have to do the quizz again to get 100%

**Comment by remisharrock** [comment]
From the forum : 

Keep in mind this is a beginning C Programming course and the instructors are most likely teaching best practices as absolute rules regarding creating and assigning variables, instead of explaining the available intricate options.

Yes but best practices are not absolute rules. If the program won't compile we need to know the truth about what is wrong with it.

 
posté il y a about 20 hours par ruin_christmas

indeed we have to differentiate between good practice and the different C standards (ANSI C, C99, C11, C18) .. we could add a textual explanation underneath the codecast. let me check with the pedagogical team

**Comment by petraBT** [comment]
I think this issue is now gone - there was an error in the quiz. I don't think confusion will persist now that the quiz is correct.

**Comment by Kitkatniss** [comment]
#20 #33 #43 told you...

I've just checked, it's still the same issues

**Comment by Kitkatniss** [comment]
#63 is the same

**Comment by remisharrock** [comment]
Thank you for referencing duplicate issues @Kitkatniss  ! we will close them also :)
