### ISSUE TITLE
Issue with quiz about compilation in course 6

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#661]
It seems that quiz interface won't let instructions to be displayed on several lines.  
For last question of [quiz about compilation](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020/courseware/632a112f8d4e46c88cf195f34e486a4f/5a68ec5063644f41986eb24655613ab1/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B1T2020%2Btype%40discussion%2Bblock%4055c7da0e5e9244ab9c8066477df744e3), expected answer which is :  

```
gcc prog.c
./a.out
```
appears on a single line:
`gcc prog.c ./a.out`

Clearly, this will raise an error if executed in weblinux.

Here, you could imply add a semi-colon between the two instructions, but there is the same kind of problem in course 1, for the quiz about naming and declaring variables.

**Comment by AadhyaKocha** [comment]
Should I add a note for the same or are we assuming the learner still understands this commands nonetheless?

**Comment by mblockelet** [comment]
I removed the CSS style which was preventing newlines. However, it can cause issues on other quizzes if the task writer had left extra newlines, but looking at various quizzes none seem to have the issue.

**Comment by remisharrock** [comment]
thank you @mblockelet we will check if other quizzes are OK now !

**Comment by deladan** [comment]
Hello, 

Issue is still there with the last question of the [quiz about declaring and naming variables](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551).  
As I've already said though, I think it would make more sense if semi-colons were added and that expected answer was changed to "These variables are independent of each other."

**Comment by AadhyaKocha** [comment]
Is this the same as [France-ioi/taskgrader#93](France-ioi/taskgrader#93) which Michel says is solved? If not can you please elaborate on the issue for me?

**Comment by deladan** [comment]
Hello AadhyaKocha,

Link comes to a page not found error message.
Actually, issue came from the fact that we couldn't write several lines in some quiz question.
Therefore, question didn't make real sense.
Code appears on several lines now.  


However, I really think that question should be modified (adding the semi-colons so code were correctly written), and that expected answer should be that there are two different variables rather than raising two compilation errors.
It would make more sense with the section's topic, making sure learner understands C is case-sensitive.

**Comment by mblockelet** [comment]
Hello,

When I look at the last question of the quiz, it is written on multiple lines as asked (that was the fix I did a month ago, and that AadhyaKocha is referring to). Here's a screenshot of how it looks for me :

![image](https://user-images.githubusercontent.com/11016337/103803694-cea94800-5048-11eb-9351-be5198e0a69a.png)

If you see the question on one line, could you send me a screenshot, along with which browser and version you are using, so I can investigate?

Thank you!

**Comment by deladan** [comment]
Hello mblockelet,

When I wrote this comment, instructions still appeared on one line.  
Now, it is indeed fixed.  
Sorry if I wasn't very clear about it.  

I still think question should be modified to make more sense with section's contents though.

**Comment by AadhyaKocha** [comment]
Great! I will follow up with @remisharrock later on whether we should change the question with the semicolons and then answer changed accordingly. But good to know that the line change is indeed fixed.

**Comment by deladan** [comment]
[Another post from a learner](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/517e9b8f3b9731adf777bfbf13276713572ea886/threads/5ffdb726cfe4fd0811250f2c) who are confused about the question.

**Comment by AadhyaKocha** [comment]
Made the change now.
